image:
  repository: docker.io/geowalrus/petclinic
  tag: 3.2.0-SNAPSHOT-86
fullnameOverride: petclinic
replicaCount: 1
service:
  port: 8001
livenessProbe:
  httpGet:
    path: /
    port: http
readinessProbe:
  httpGet:
    path: /
    port: http
startupProbe:
  httpGet:
    path: /
    port: http
